== Modules overview

This project contains 1 singleton module and 0 cloneable module.

.Modules list
[cols="", %autowidth, frame=all, grid=all, stripes=none]
|===
|Singleton |Cloneable

|<<DeviceManager.lvlib>>
|
|===

This graph represents the links between all DQMH modules.

[graphviz, format="png", align="center"]
....
digraph G503347 {
rankdir=LR;
edge[dir=both color=black  arrowhead=normal arrowtail=none style=filled penwidth=1]
node[color=black shape=box]
"DeviceManager"[color=black shape=component]
"GenericDevice.lvclass:Send Receive Parse"[color=skyblue shape=note]
"DeviceManager" -> "DeviceManager" [label="    " dir=both color=forestgreen  arrowhead=normal arrowtail=vee style=filled penwidth=1];
"GenericDevice.lvclass:Send Receive Parse" -> "DeviceManager" [label="    " dir=both color=forestgreen  arrowhead=normal arrowtail=vee style=filled penwidth=1];
"DeviceManager" -> "DeviceManager" [label=" " dir=both color=goldenrod  arrowhead=normal arrowtail=none style=dashed penwidth=1];
}
....
