== Classes overview

This project contains 5 classes and 0 interface.

.Classes list
[cols="", %autowidth, frame=all, grid=all, stripes=none]
|===
|Classes |Interfaces

|<<Communicator.lvclass>>
|

|<<GenericDevice.lvclass>>
|

|<<Monochromator.lvclass>>
|

|<<CCD.lvclass>>
|

|<<SCD.lvclass>>
|
|===

[plantuml, format="svg", align="center"]
....
@startuml
set namespaceSeparator :
skinparam ClassBackgroundColor #FFFFFF
skinparam ClassBorderColor #555555
skinparam ClassFontColor #000000
skinparam ClassHeaderBackgroundColor #808080

skinparam top to bottom direction
class "Communicator" {
{field} -WebSocket Connection : LV Class
{field} -ID counter : I32
{field} -connectionEstablished? : Boolean
{static} {method} +JSON Parse Command()
{static} {method} +JSON Parse Errors()
{static} {method} +JSON Parse ID()
{static} {method} +JSON Parse Info()
{static} {method} +JSON Parse Results()
{static} {method} +Overwrite ID()
{method} +OpenConnection()
{method} +CloseConnection()
{method} +SendAndAskForReply()
{method} #ReceiveJson()
{method} #SendJson()

}
"Communicator" *-- "WebSockets.lvlib:WebSocket Client"


class "GenericDevice" {
{field} -deviceTerm : String
{field} -deviceType : String
{field} -index : I32
{field} -open : Boolean
{field} -serialNumber : String
{field} +productId : I32
{static} {method} +Send Receive Parse()
{static} {method} +ReadDeviceJSONList()
{static} {method} +DecodeDeviceJSONList()
{static} {method} +ReadDeviceTypeAsString()
{method} +DeviceClose()
{method} +DeviceOpen()
{method} +DeviceIsOpen()

}


class "Monochromator" {
{static} {method} +setPosition()
{static} {method} +getFilterWheelPosition()
{static} {method} +moveFilterWheel()
{static} {method} +getGratingPosition()
{static} {method} +moveGrating()
{static} {method} +getMirrorPosition()
{static} {method} +moveMirror()
{static} {method} +getPosition()
{static} {method} +moveToPosition()
{static} {method} +getShutterStatus()
{static} {method} +shutterClose()
{static} {method} +shutterOpen()
{static} {method} +getSlitPositionInMM()
{static} {method} +moveSlitMM()
{static} {method} +getConfig()
{static} {method} +Init()
{static} {method} +isBusy()
{static} {method} +isInitialized()
{static} {method} -parseConfigData()
{method} +DeviceClose()
{method} +DeviceIsOpen()
{method} +DeviceOpen()

}
"GenericDevice" <|-- "Monochromator"


class "CCD" {
{static} {method} +getSpeedAndGainSettings()
{static} {method} +parseConfigData()
{static} {method} +parseImageData()
{static} {method} +parseRangeMode()
{static} {method} +parseSpectralData()
{static} {method} +sortGetConfig()
{static} {method} +acquisitionAbort()
{static} {method} +acquisitionStart()
{static} {method} +calculateRangeModePositions()
{static} {method} +getAcqCount()
{static} {method} +getAcquisitionBusy()
{static} {method} +getAcquisitionData()
{static} {method} +getAcquisitionReady()
{static} {method} +getChipTemperature()
{static} {method} +getCleanCount()
{static} {method} +getConfig()
{static} {method} +getDataSize()
{static} {method} +getExposureTime()
{static} {method} +getFitParams()
{static} {method} +getGain()
{static} {method} +getParallelSpeed()
{static} {method} +getSignalOut()
{static} {method} +getSpeed()
{static} {method} +getTimerResolution()
{static} {method} +getTriggerIn()
{static} {method} +getXAxisConversionType()
{static} {method} +restart()
{static} {method} +setAcqCount()
{static} {method} +setAcqFormat()
{static} {method} +setCenterWavelength()
{static} {method} +setCleanCount()
{static} {method} +setExposureTime()
{static} {method} +setGain()
{static} {method} +setParallelSpeed()
{static} {method} +setRoi()
{static} {method} +setSignalOut()
{static} {method} +setSpeed()
{static} {method} +setTimerResolution()
{static} {method} +setTriggerIn()
{static} {method} +setXAxisConversionType()
{static} {method} +Setup Example()
{static} {method} +Teardown Example()
{static} {method} +Example - Open Close CCD()
{static} {method} +Example - Get Config()
{static} {method} +CCD Example()
{method} +DeviceClose()
{method} +DeviceIsOpen()
{method} +DeviceOpen()
{method} +getChipSize()

}
"GenericDevice" <|-- "CCD"


class "SCD" {
{method} +DeviceClose()
{method} +DeviceOpen()
{method} +DeviceIsOpen()

}
"GenericDevice" <|-- "SCD"



@enduml
....
